/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: { 'baloo': ['"Baloo 2"', 'cursive', 'sans-serif'] },
      colors: {
        'primary-blue': '#3A86FF',
        'primary-blue-dark': '#005AD9',
        'accent-yellow': '#FFBE0B',
        'accent-green': '#52B788',
        'accent-red': '#FB5607',
        'accent-purple': '#8338EC',
        'accent-pink': '#FF006E',
        'bg-page': '#FFFDF7',
        'bg-surface': '#FFFFFF',
        'text-primary': '#433E51',
        'text-secondary': '#8B8299',
        'island-animals': '#FF9F1C',
        'island-fruits': '#52B788',
        'island-objects': '#3A86FF',
        'island-nature': '#22C55E',
        'island-colors': '#EC4899',
      },
      borderRadius: { 'soft': '24px' },
      boxShadow: {
        'soft': '0px 4px 12px rgba(67, 62, 81, 0.15)',
        'strong': '0px 8px 16px rgba(67, 62, 81, 0.2)',
        'glow-yellow': '0 0 24px rgba(255, 190, 11, 0.6)',
        'button-3d': 'inset 0 -6px 0 0 #005AD9',
        'button-3d-yellow': 'inset 0 -6px 0 0 #E5A800',
        'button-3d-green': 'inset 0 -6px 0 0 #3D8A66',
      },
      fontSize: {
        'h2': ['48px', { lineHeight: '1.3', fontWeight: '700' }],
        'h2-mobile': ['36px', { lineHeight: '1.3', fontWeight: '700' }],
        'h3-mobile': ['28px', { lineHeight: '1.4', fontWeight: '700' }],
        'body': ['22px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-mobile': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'small': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'small-mobile': ['16px', { lineHeight: '1.5', fontWeight: '600' }],
      },
      keyframes: {
        'bounce-in': { '0%': { transform: 'scale(0)', opacity: '0' }, '50%': { transform: 'scale(1.1)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'shake': { '0%, 100%': { transform: 'translateX(0)' }, '25%': { transform: 'translateX(-10px)' }, '75%': { transform: 'translateX(10px)' } },
        'pulse-glow': { '0%, 100%': { boxShadow: '0 0 20px rgba(255, 190, 11, 0.4)' }, '50%': { boxShadow: '0 0 40px rgba(255, 190, 11, 0.8)' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        'pop': { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.2)' }, '100%': { transform: 'scale(1)' } },
        'slide-up': { '0%': { transform: 'translateY(100%)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'wiggle': { '0%, 100%': { transform: 'rotate(-3deg)' }, '50%': { transform: 'rotate(3deg)' } },
      },
      animation: {
        'bounce-in': 'bounce-in 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'shake': 'shake 0.5s ease-in-out',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'pop': 'pop 0.3s ease-in-out',
        'slide-up': 'slide-up 0.5s ease-out',
        'wiggle': 'wiggle 0.5s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}